### PR TITLE
Default value to date

### PR DESCRIPTION
**Pull request by anishamalde**
**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged

### CODE REVIEW

**Comment by Loque-** [comment]
Hey @anishamalde, thanks again - sorry for the slowness on this one going through: https://github.com/UKHomeOffice/govuk-react/pull/370 but I think this does the same thing and is just about to be merged today!

**Comment by Joe-Brady** [comment]
@Loque- I just had a look at 370, can't see anything in there about setting the default values?

**Comment by Joe-Brady** [comment]
Also, we're not sure what's happening with the failing test - I had a look at Master and that seemed to be failing on the same test - is that a known issue or something we've maybe not done on our end?

**Comment by Loque-** [comment]
@Joe-Brady Ah, yes you are right, that does not do defaultValues, I'll look have a better look at these now.

CI is failing on codecov from the fork; Alasdair had a look on this one: https://github.com/UKHomeOffice/govuk-react/pull/406#issuecomment-420250370

This specific PR does also have some failing Eslint tests, but all pretty quick to adjust - are you able to view the details on the travis process? I get a `Details` link which I can click through for the explanation;

screen shot 2018-09-11 at 15 13 08

**Comment by Loque-** [comment]
Just going to close this as it has been superseded by https://github.com/UKHomeOffice/govuk-react/pull/408, cheers!

**Pull request closed without merging**
