### PR TITLE
Add contributors to Readme

### PR DESCRIPTION
**Pull request by gavinorland**
Quick one!

**Checklist**:

* [ ] Documentation N/A
* [ ] Tests N/A
* [x] Ready to be merged

### CODE REVIEW

**Comment by gavinorland** [comment]
That was already ignored! Are people happy with me changing it to that? :smile:

**Comment by Loque-** [comment]
They are alphabetically ordered by first name, no? : D

**Comment by gavinorland** [comment]
Oh, I thought it was just the order that people had come along and worked on it and that was chance. Shall we do it by surname, or first name?

**Comment by Loque-** [comment]
They are currently ordered alphabetically by first name so, just copy that? : )

**Comment by gavinorland** [comment]
I can't merge this because required checks haven't completed, but if anybody else can that would be great.

**Pull request merged**
