### PR TITLE
Feature/improve date input types

### PR DESCRIPTION
**Pull request by Loque-**
- Change text to number for input field types
- Remove unwanted className on label component

* [x] Documentation
* [x] Tests
* [x] Ready to be merged

### CODE REVIEW

**Comment by Loque-** [comment]
Aye thanks for that - it was literally just to address a reported issue with autocomplete suggestions, and I noticed we didn’t match the GDS input types... but I did observe some HTML5 validation prop that could be copied and mitigate against your invalid inputs observation... I’ll add it shortly! Thanks!

**Comment by Loque-** [comment]
I'm not sure we can turn autocomplete off as it is a browser feature - I'd argue it is out of scope for us also as this component library needs to follow GDS as closely as possible; https://design-system.service.gov.uk/components/date-input/

I can check default values however, it should be possible, but I am not sure if it is yet; I'll make the adjustment if needed!

**Comment by penx** [comment]
Deploy preview for *affectionate-nobel-f3a8ec* processing.

Built with commit 7b7620dd5f1df7c5429f2957d2c8422fbe21b25b

https://app.netlify.com/sites/affectionate-nobel-f3a8ec/deploys/5bd2f6021f12b737047ab1f6

**Comment by penx** [comment]
Something weird is going on with the CI reports here. There are only 3 changed files but Chromatic and CodeCov seem to be reporting a lot of changes. May merge this in, along with our other PRs and give everything a smoke test afterwards

**Comment by penx** [comment]
Current master:
```
--------------------------------------------------|----------|----------|----------|----------|-------------------|
File                                              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                         |    99.74 |    98.79 |    97.35 |    99.73 |                   |
```

**Comment by gavinorland** [comment]
Test coverage tantalisingly close to 💯 % !

**Pull request merged**
